application: map-of-life
version: beta
module: tree-pruner

instance_class: B4_1G
basic_scaling:
  max_instances: 20
  idle_timeout: 30s

runtime: python27
threadsafe: true
api_version: 1
skip_files: |
    ^(.*/)?(
    (app\.yaml)|
    (index\.yaml)|
    (\..*)|
    (node_modules/.*) |
    (Gruntfile.js) |
    (bower.js) |
    (.*\.pyc)|
    (.*\.bat)|
    (.*\.psd)|
    (Thumbs.db)|
    (.*\.svn/.*)|
    (.*\.lnk)|
    (.*\.datastore)|
    (_darcs/.*)|
    (.*\.swp)|
    (.*\.log)|
    )$

inbound_services:
- warmup

builtins:
- remote_api: on
- deferred: on

handlers:

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /api/.*
  script: prune_handler.application

libraries:
- name: webapp2
  version: "2.5.2"

- name: pycrypto
  version: "2.3"

- name: numpy
  version: "latest"

- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"

- name: matplotlib
  version: latest
